### ISSUE TITLE
`current_metrics` and `metrics` in the table `kubernetes_horizontal_pod_autoscaler` return NULL

### ISSUE THREAD

**Issue by dexye-apt** [turbot/steampipe-plugin-kubernetes#184]
**Describe the bug**
The column `current_metrics` and `metrics` in the table `kubernetes_horizontal_pod_autoscaler` always return NULL

**Steampipe version (`steampipe -v`)**
Example: v0.21.1

**Plugin version (`steampipe plugin list`)**
kubernetes v0.25.1

**To reproduce**
`select * from kubernetes_horizontal_pod_autoscaler`

**Expected behavior**
The column `current_metrics` and `metrics` should return the specification of the HPA. However, those two columns always return NULL while the other columns return solid data. 

**Additional context**
[Slack Reference](https://turbot-community.slack.com/archives/C01UECB59A7/p1697586457466929)
Ved Misra confirm the k8s plugin is referencing incorrect fields [here](https://github.com/turbot/steampipe-plugin-kubernetes/blob/main/kubernetes/table_kubernetes_horizontal_pod_autoscaler.go#L51).

**Comment by bigdatasourav** [comment]
To Fix the `incompatible versions` [issue](https://github.com/turbot/steampipe-plugin-kubernetes/pull/126/files#diff-57937828cba5074f89063d4de994c051fe92fc539f5db03342120bd65b0da706L7), we downgraded the API from v2beta2 to V1 which resulted in the above issue as in V1 the above columns does not come in API response. 

Since API version V2 is available for HPA, I have raised a [PR](https://github.com/turbot/steampipe-plugin-kubernetes/pull/190) for this issue. We may get the `incompatible versions` issue if someone uses older K8s versions.
